-- Keep public learner forms on the anonymous role and remove avoidable
-- overlapping RLS policies. These indexes support the foreign-key and
-- rate-limit lookups introduced by the security hardening migration.

alter table private.public_submission_rate_limits
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'private.public_submission_rate_limits'::regclass
      and contype = 'p'
  ) then
    alter table private.public_submission_rate_limits
      add constraint public_submission_rate_limits_pkey primary key (id);
  end if;
end;
$$;

create index if not exists admin_audit_log_actor_id_idx
  on public.admin_audit_log (actor_id);

create index if not exists guru_pengguna_approved_by_idx
  on public.guru_pengguna (approved_by)
  where approved_by is not null;

drop policy if exists "Teachers read own approval" on public.guru_pengguna;
drop policy if exists "Admins manage approved teachers" on public.guru_pengguna;

create policy "Teachers or admins read approved teachers" on public.guru_pengguna
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or exists (
      select 1 from public.admin_pengguna admin
      where admin.user_id = (select auth.uid())
    )
  );

create policy "Admins add approved teachers" on public.guru_pengguna
  for insert to authenticated
  with check (exists (
    select 1 from public.admin_pengguna admin
    where admin.user_id = (select auth.uid())
  ));

create policy "Admins update approved teachers" on public.guru_pengguna
  for update to authenticated
  using (exists (
    select 1 from public.admin_pengguna admin
    where admin.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.admin_pengguna admin
    where admin.user_id = (select auth.uid())
  ));

create policy "Admins remove approved teachers" on public.guru_pengguna
  for delete to authenticated
  using (exists (
    select 1 from public.admin_pengguna admin
    where admin.user_id = (select auth.uid())
  ));

drop policy if exists "Rate limited public book suggestions" on public.cadangan_buku;
create policy "Rate limited public book suggestions" on public.cadangan_buku
  for insert to anon
  with check (
    char_length(trim(nama)) between 3 and 120
    and char_length(trim(kelas)) between 2 and 40
    and char_length(trim(tajuk)) between 2 and 200
    and (pengarang is null or char_length(trim(pengarang)) between 2 and 160)
    and (sebab is null or char_length(trim(sebab)) <= 700)
    and kategori in ('Buku', 'Majalah', 'Bahan Digital', 'Komik Ilmiah')
    and sumber = 'Pelajar'
    and status = 'Baru'
    and susunan = 0
    and private.check_public_submission_rate('cadangan_buku', 5, interval '15 minutes')
  );

drop policy if exists "Rate limited public PSS loans" on public.pss_pinjaman;
create policy "Rate limited public PSS loans" on public.pss_pinjaman
  for insert to anon
  with check (
    char_length(trim(nama)) between 3 and 120
    and char_length(trim(kelas)) between 2 and 40
    and peranan in ('Murid', 'Pengawas PSS')
    and char_length(trim(bahan)) between 2 and 200
    and (kod_bahan is null or char_length(trim(kod_bahan)) <= 60)
    and (catatan is null or char_length(trim(catatan)) <= 500)
    and tarikh_pulang >= tarikh_pinjam
    and tarikh_pulang <= tarikh_pinjam + 90
    and status = 'Direkodkan'
    and private.check_public_submission_rate('pss_pinjaman', 3, interval '15 minutes')
  );
