-- Platform hardening: shared status vocabulary, reporting, audit history,
-- safe public booking data and kiosk-safe clinic RPCs.

-- ---------------------------------------------------------------------------
-- PSS status and admin access
-- ---------------------------------------------------------------------------
update public.pss_book
set status = case lower(trim(coalesce(status, '')))
  when 'dipinjam' then 'Dipinjam'
  when 'hilang' then 'Hilang'
  when 'rosak' then 'Rosak'
  when 'dipulangkan' then 'Dipulangkan'
  else 'Tersedia'
end
where status is null or status not in ('Tersedia', 'Dipinjam', 'Hilang', 'Rosak', 'Dipulangkan');

update public.pss_pinjaman
set status = case lower(trim(coalesce(status, '')))
  when 'dipinjam' then 'Dipinjam'
  when 'dipulangkan' then 'Dipulangkan'
  when 'lewat' then 'Lewat'
  when 'hilang' then 'Hilang'
  when 'dibatalkan' then 'Dibatalkan'
  else 'Direkodkan'
end
where status is null or status not in ('Direkodkan', 'Dipinjam', 'Dipulangkan', 'Lewat', 'Hilang', 'Dibatalkan');

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'pss_book_status_check') then
    alter table public.pss_book add constraint pss_book_status_check
      check (status in ('Tersedia', 'Dipinjam', 'Hilang', 'Rosak', 'Dipulangkan'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pss_pinjaman_status_check') then
    alter table public.pss_pinjaman add constraint pss_pinjaman_status_check
      check (status in ('Direkodkan', 'Dipinjam', 'Dipulangkan', 'Lewat', 'Hilang', 'Dibatalkan'));
  end if;
end $$;

create index if not exists pss_book_status_kategori_idx on public.pss_book (status, kategori);
create index if not exists pss_pinjaman_status_tarikh_idx on public.pss_pinjaman (status, tarikh_pinjam desc);

drop policy if exists "Admin PSS reads loans" on public.pss_pinjaman;
create policy "Admin PSS reads loans" on public.pss_pinjaman
  for select to authenticated
  using (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())));

drop policy if exists "Admin PSS updates loans" on public.pss_pinjaman;
create policy "Admin PSS updates loans" on public.pss_pinjaman
  for update to authenticated
  using (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())));

drop policy if exists "Admin PSS manages books" on public.pss_book;
create policy "Admin PSS manages books" on public.pss_book
  for all to authenticated
  using (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())));

-- ---------------------------------------------------------------------------
-- Admin audit trail
-- ---------------------------------------------------------------------------
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  record_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_table_record_idx on public.admin_audit_log (table_name, record_id);
alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;
grant select on public.admin_audit_log to authenticated;
drop policy if exists "Admins read audit log" on public.admin_audit_log;
create policy "Admins read audit log" on public.admin_audit_log
  for select to authenticated
  using (exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid())));

create or replace function public.record_admin_audit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  actor uuid := auth.uid();
  old_record jsonb := case when TG_OP in ('UPDATE', 'DELETE') then to_jsonb(OLD) else null end;
  new_record jsonb := case when TG_OP in ('INSERT', 'UPDATE') then to_jsonb(NEW) else null end;
  record_key text := coalesce(new_record->>'id', old_record->>'id');
begin
  if actor is null or not exists (select 1 from public.admin_pengguna a where a.user_id = actor) then
    return coalesce(NEW, OLD);
  end if;
  insert into public.admin_audit_log (actor_id, action, table_name, record_id, metadata)
  values (actor, TG_OP, TG_TABLE_NAME, record_key, jsonb_build_object('old', old_record, 'new', new_record));
  return coalesce(NEW, OLD);
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'pss_book', 'pss_pinjaman', 'tempahan', 'content_block', 'pengumuman',
    'gallery_item', 'nilam_stat', 'resource_file', 'school_directory', 'staff',
    'takwim', 'cadangan_buku'
  ] loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists admin_audit_%I on public.%I', table_name, table_name);
      execute format('create trigger admin_audit_%I after insert or update or delete on public.%I for each row execute function public.record_admin_audit()', table_name, table_name);
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Safe public booking view. Private user identity and admin fields remain on
-- the base table, while public timetable pages use this view.
-- ---------------------------------------------------------------------------
create index if not exists tempahan_user_id_idx on public.tempahan (user_id);
drop policy if exists "baca semua" on public.tempahan;
revoke select on public.tempahan from anon;

drop policy if exists "Users and admins read bookings" on public.tempahan;
create policy "Users and admins read bookings" on public.tempahan
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or exists (select 1 from public.admin_pengguna a where a.user_id = (select auth.uid()))
  );

create or replace view public.tempahan_awam as
select id, bilik, tarikh, masa_mula, masa_tamat, label, kumpulan, nama_pemohon,
       kelas, tujuan, guna_lcd, status, created_at
from public.tempahan
where status = 'aktif';

grant select on public.tempahan_awam to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Kiosk clinic RPCs: no direct table access, exact IC lookup, minimal fields.
-- ---------------------------------------------------------------------------
create or replace function public.klinik_cari(p_ic text)
returns table (nama text, kelas text, rekod jsonb)
language plpgsql
security definer
set search_path = private, public, pg_catalog
as $$
declare
  normalized_ic text := regexp_replace(coalesce(p_ic, ''), '[^0-9]', '', 'g');
begin
  if normalized_ic !~ '^[0-9]{12}$' then
    raise exception 'Nombor IC mesti mengandungi 12 digit.' using errcode = '22023';
  end if;
  return query
  select m.nama, m.kelas,
    coalesce(jsonb_agg(jsonb_build_object(
      'tarikh', to_char(r.tarikh at time zone 'Asia/Kuala_Lumpur', 'YYYY-MM-DD'),
      'masa', to_char(r.tarikh at time zone 'Asia/Kuala_Lumpur', 'HH24:MI'),
      'sebab', r.sebab
    ) order by r.tarikh desc) filter (where r.id is not null), '[]'::jsonb)
  from private.murid_klinik m
  left join private.rekod_klinik r on r.no_ic = m.no_ic
  where m.no_ic = normalized_ic
  group by m.no_ic, m.nama, m.kelas;
end;
$$;

create or replace function public.klinik_daftar(p_ic text, p_sebab text)
returns table (nama text, kelas text, rekod jsonb)
language plpgsql
security definer
set search_path = private, public, pg_catalog
as $$
declare
  normalized_ic text := regexp_replace(coalesce(p_ic, ''), '[^0-9]', '', 'g');
  cleaned_sebab text := trim(coalesce(p_sebab, ''));
begin
  if normalized_ic !~ '^[0-9]{12}$' then
    raise exception 'Nombor IC mesti mengandungi 12 digit.' using errcode = '22023';
  end if;
  if char_length(cleaned_sebab) not between 2 and 300 then
    raise exception 'Sebab ke klinik mesti antara 2 hingga 300 aksara.' using errcode = '22023';
  end if;
  if not exists (select 1 from private.murid_klinik where no_ic = normalized_ic) then
    raise exception 'Rekod murid tidak ditemui.' using errcode = 'P0002';
  end if;
  if exists (
    select 1 from private.rekod_klinik
    where no_ic = normalized_ic and sebab = cleaned_sebab and tarikh > now() - interval '2 minutes'
  ) then
    raise exception 'Lawatan yang sama baru sahaja direkodkan.' using errcode = '23505';
  end if;
  insert into private.rekod_klinik (no_ic, sebab) values (normalized_ic, cleaned_sebab);
  return query select * from public.klinik_cari(normalized_ic);
end;
$$;

revoke execute on function public.klinik_cari(text) from public, anon;
revoke execute on function public.klinik_daftar(text, text) from public, anon;
grant execute on function public.klinik_cari(text) to anon, authenticated;
grant execute on function public.klinik_daftar(text, text) to anon, authenticated;
